In [1]:
import random
import numpy as np

In [2]:
arr1 = np.random.randint(0, 10, size=(1, 8))
arr1

array([[8, 2, 8, 1, 5, 4, 0, 6]])

In [3]:
len(arr1)

1

In [4]:
lis = [1, 2, 3, 4, 5, 6, 7, 8]
len(lis)

8

In [5]:
np.linspace(1, 9, 10)

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
iput = input()

asd


In [8]:
lis = iput.split(' ')

In [9]:
lis

['asd']

In [10]:
lis[-1]

'asd'

In [11]:
lis.index('L')

ValueError: 'L' is not in list

In [ ]:
lis[11]

In [ ]:
lis = [int(x) for x in lis]

In [ ]:
lis

In [ ]:
lis.remove(5)

In [ ]:
lis

In [ ]:
lis = ['A', 'B', 'C']

class Node:
    def __init__(self, val = None):
        self.valu = val
        self.left = None
        self.right = None
    
    def value(self, mode, root):
        exec("root.{} = 100" .format(mode))
        print(root.left)
        
node = Node()
node.value('left', node)

for item in lis:
    exec("{} = Node(1000)" .format(item))
    
for item in lis:
    exec("print({}.valu)" .format(item))

In [ ]:
print("{0} = {0} but not {1}" .format(0, 1))

In [ ]:
lis = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']
lisTwo = ['B', 'A', 'D', 'C', 'E', 'L', 'G', 'F', 'K', 'H', 'J', 'I']

maxIndex = 0

for item in lis:
    if lisTwo.index(item) > maxIndex:
        maxIndex = lisTwo.index(item)
lisTwo[maxIndex]

In [ ]:
lis.append('F')

In [ ]:
print(lis)
lis.remove('F')
lis

In [ ]:
D E B F C A
D B E A F C

In [ ]:
PostOrder = input("\nEnter Post Order : ")
InOrder = input("\nEnter In Order : ")

PostOrder = PostOrder.split(' ')
InOrder = InOrder.split(' ')

In [ ]:
# Construct tree from inorder and post order

class Node:
    def __init__(self, val = None):
        self.value = val
        self.left = None
        self.right = None

class BinaryTree:
    def __init__(self):
        self.root = None
    
    def PreOrder(self, node):
        if node:
            #temp = None
            print(exec("{}.{}" .format(node, 'value')))
            #print(f"{temp} -> ", end="")
            self.PreOrder(node.left)
            self.PreOrder(node.right)

    def ConsTree(self, lis, PostOrder, root, mode):
        maxIndex = 0

        for item in lis:
            if PostOrder.index(item) > maxIndex:
                maxIndex = PostOrder.index(item)
        
        exec("{}.{} = {}" .format(root, mode, PostOrder[maxIndex]))
        print("main : ", PostOrder[maxIndex])
        
        try:
            lefty = lis[0:lis.index(PostOrder[maxIndex])]
            print("leftty : ", lefty)
        except:
            lefty = []
        
        try:
            righty = lis[lis.index(PostOrder[maxIndex])+1:]
            print("righty : ", righty)
        except:
            righty = []

        if len(lefty) == 1:
            exec("{}.left = lefty[0]" .format(PostOrder[maxIndex]))
            print("left : ", lefty[0])
        elif len(lefty) > 1:
            self.ConsTree(lefty, PostOrder, PostOrder[maxIndex], 'left')
        else:
            pass

        if len(righty) == 1:
            exec("{}.left = righty[0]" .format(PostOrder[maxIndex]))
            print("right : ", righty[0])
        elif len(righty) > 1:
            self.ConsTree(righty, PostOrder, PostOrder[maxIndex], 'right')
        else:
            pass



if __name__ == "__main__":
    bt = BinaryTree()
    
    PostOrder = input("\nEnter Post Order : ")
    InOrder = input("\nEnter In Order : ")

    PostOrder = PostOrder.split(' ')
    InOrder = InOrder.split(' ')

    PostOrder = ['D', 'E', 'B',  'F',  'C',  'A']
    InOrder = ['D', 'B', 'E', 'A', 'F', 'C']

    for item in PostOrder:
        exec("{0} = Node(item)" .format(item))
    
    root = PostOrder[-1]
    left = InOrder[0:InOrder.index(root)]
    print("left list : ", left)
    
    try:
        right = InOrder[InOrder.index(root)+1:]
        print("right : ", right)
    except:
        right = []

    bt.ConsTree(left, PostOrder, root, 'left')
    bt.ConsTree(right, PostOrder, root, 'right')

    #exec("bt.PreOrder({})" .format(root))

In [ ]:
numArr = np.zeros([3, 3])
numArr

In [ ]:
numArr[2][2] =1
numArr

In [ ]:
int(1.)

In [ ]:
lis = [1, 2, 3, 4]

In [ ]:
lis.pop(2)

In [ ]:
lis

In [ ]:
# breadth first search traversal
import numpy as np

if __name__ == "__main__":
    numNode = int(input("\nEnter Number Of Nodes : "))
    nodeArr = np.zeros([numNode, numNode])

    queue = []
    res = []

    def ConnectNode():
        first = int(input("\nEnter first Node : "))
        second = int(input("Enter Second Node : "))
        
        nodeArr[first][second] = 1
        print("\nNode Connected!")

    def BFS(node, queue, res):
        #queue.append(node)

        for i in range(0, numNode):
            if int(nodeArr[node][i]) == 1 and nodeArr[node][i] not in queue:
                queue.append(nodeArr[node][i])
        
        res.append(queue.pop(0))
        print(res)
        BFS(queue[0], queue, res)

    queue.append(0)

    while True:
        choice = int(input("\n1. Connect\n2. BFS\nChoice : "))
        
        if choice is 1:
            ConnectNode()
        elif choice is 2:
            print(nodeArr)
            BFS(0, queue, res)
            print(res)

    


In [25]:
dic = {1:['A', 'C'], 2:'B'}
dic

{1: ['A', 'C'], 2: 'B'}

In [26]:
for i, j in dic.items():
    print(i, j)

1 ['A', 'C']
2 B


In [27]:
list(dic.keys())[0]

1

In [28]:
for i in dic[1]:
    print(i)

A
C


In [29]:
lis = [1, 2, 3, 4, 5, 6, 7, 8]
lis

[1, 2, 3, 4, 5, 6, 7, 8]

In [30]:
lis.pop(-1)

8

In [1]:
graph = {'A' : [('A', 'C', 3)], 'B' : [('B', 'C', 10), ('B', 'D', 4)], 'C' : [('A', 'C', 3), ('B', 'C', 10), ('C', 'D', 2), ('C', 'E', 6)], 'D' : [('C', 'D', 2), ('D', 'E', 1)], 'E' : [('C', 'E', 6), ('D', 'E', 1)]}
graph

{'A': [('A', 'C', 3)],
 'B': [('B', 'C', 10), ('B', 'D', 4)],
 'C': [('A', 'C', 3), ('B', 'C', 10), ('C', 'D', 2), ('C', 'E', 6)],
 'D': [('C', 'D', 2), ('D', 'E', 1)],
 'E': [('C', 'E', 6), ('D', 'E', 1)]}

In [4]:
for sets in graph.values():
    for item in sets:
        print(item)

('A', 'C', 3)
('B', 'C', 10)
('B', 'D', 4)
('A', 'C', 3)
('B', 'C', 10)
('C', 'D', 2)
('C', 'E', 6)
('C', 'D', 2)
('D', 'E', 1)
('C', 'E', 6)
('D', 'E', 1)


In [5]:
lis = [1, 2, 3, 4]
listemp = lis.copy()
print(lis, listemp)

[1, 2, 3, 4] [1, 2, 3, 4]


In [6]:
listemp.pop(0)
listemp

[2, 3, 4]

In [7]:
lis

[1, 2, 3, 4]

In [1]:
dic = {1 : [1, 2, 3, 4], 2 : [2, 3, 4, 5]}

In [2]:
dic

{1: [1, 2, 3, 4], 2: [2, 3, 4, 5]}

In [3]:
len(dic)

2

In [2]:
random.randint(0, 10)

9

In [3]:
lis = ['A', 'B', 'C', 'E', 'D', 'Z', 'X', 'I', 'J']
lis.sort()
lis

['A', 'B', 'C', 'D', 'E', 'I', 'J', 'X', 'Z']

In [6]:
lis = ['Anjali', 'Aman', 'Mihir', 'Sweta', 'Mayur', 'Kiki', 'Chand', 'Abhik']
lis.sort()
name = input("\nEnter Name : ")


Enter Name : Mihir


In [4]:
def BinarySearch(begin, end, num):
    if begin >= end:
        print("\nnumber Not found!")
    elif num > lis[int((begin+end)/2)]:
        begin = int((begin+end)/2) + 1
        print(f"\nbegin : {begin}\nEnd : {end}")
        BinarySearch(begin, end, num)

    elif num < lis[int((begin+end)/2)]:
        end = int((begin+end)/2) - 1
        print(f"\nbegin : {begin}\nEnd : {end}")
        BinarySearch(begin, end, num)

    elif num == lis[int((begin+end)/2)]:
        print(f"\nbegin : {begin}\nEnd : {end}")
        print("\nNumber Found")

In [7]:
BinarySearch(0, 7, name)


begin : 4
End : 7

begin : 6
End : 7

begin : 6
End : 7

Number Found


In [9]:
int((0+1)/2)

0

In [10]:
lis

['Abhik', 'Aman', 'Anjali', 'Chand', 'Kiki', 'Mayur', 'Mihir', 'Sweta']

In [13]:
sorted(lis)

['Abhik', 'Aman', 'Anjali', 'Chand', 'Kiki', 'Mayur', 'Mihir', 'Sweta']

In [21]:
lis = ['Anjali', 'Aman', 'Mihir', 'Sweta', 'Mayur', 'Kiki', 'Chand', 'Abhik']
lis2 = [1, 2, 3]

In [22]:
lis[2:2] = lis2
lis

['Anjali',
 'Aman',
 1,
 2,
 3,
 'Mihir',
 'Sweta',
 'Mayur',
 'Kiki',
 'Chand',
 'Abhik']

In [20]:
lis

['Abhik',
 'Aman',
 <generator object <genexpr> at 0x0000015D913E3518>,
 [1, 2, 3],
 'Anjali',
 'Chand',
 'Kiki',
 'Mayur',
 'Mihir',
 'Sweta']

In [23]:
lis3 = [1, 2]
lis3.pop(0)
lis3.pop(0)

2

In [24]:
lis3

[]

In [25]:
lis[2:2] = lis3

In [26]:
lis

['Anjali',
 'Aman',
 1,
 2,
 3,
 'Mihir',
 'Sweta',
 'Mayur',
 'Kiki',
 'Chand',
 'Abhik']